name: 🛡️ Amla Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: read

jobs:
  amla-code-review:
    runs-on: ubuntu-latest

    steps:

      # Checkout PR repository
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Checkout Rules Repository
      - name: Checkout Amla Rules Repository
        uses: actions/checkout@v4
        with:
          repository: usha-kakde-amla/Amla-code-Reviewer
          path: external-rules
          fetch-depth: 1

      # Display rule files
      - name: List rule files
        run: |
          echo "======================================="
          echo " Markdown Rule Files"
          echo "======================================="

          ls -1 external-rules/rules/*.md 2>/dev/null || echo "No rule files found"

      # Setup .NET
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Install Tool
      - name: Install Amla Reviewer Tool
        run: |
          dotnet tool install -g AmlaCodeReviewer.Tool || true

      # Build PR URL
      - name: Set PR URL
        id: pr-url
        run: |
          PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

      # Run Reviewer
      - name: Run Amla Code Reviewer
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-flash
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |

          RULES_DIR="./external-rules/rules"

          amla-review review \
            --pr "${{ steps.pr-url.outputs.pr_url }}" \
            --rules "$RULES_DIR" \
            --output report.json \
            --suggest-rules suggested-rules.json \
            --fail-on-error

        continue-on-error: true

      # Upload report
      - name: Upload violations report
        if: hashFiles('report.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: amla-report-pr-${{ github.event.pull_request.number }}
          path: report.json

      # Upload suggested rules
      - name: Upload suggested rules artifact
        if: hashFiles('suggested-rules.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: suggested-rules-pr-${{ github.event.pull_request.number }}
          path: suggested-rules.json
